export const mainPostText = `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam varius velit at blandit aliquam. Donec a placerat erat, non aliquet erat. Fusce elementum ut quam ut dapibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce mollis sollicitudin ante at imperdiet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam et condimentum elit. Aenean condimentum pharetra iaculis. Proin in iaculis nibh.

Ut euismod auctor lacus id semper. Sed eleifend feugiat diam, ullamcorper molestie nunc auctor ac. Sed porttitor nulla neque, ut elementum enim bibendum et. Nunc hendrerit auctor lectus, at tincidunt massa elementum eu. Vivamus ligula mi, euismod id elit vitae, sagittis placerat turpis. Praesent mollis maximus risus, quis suscipit arcu sollicitudin in. Donec est sapien, convallis sed est sed, laoreet commodo mauris. Cras tristique est vel magna sagittis congue. Ut at condimentum dui, facilisis dignissim risus.

Morbi non viverra risus. Aliquam dignissim elit ac nisl tristique ornare. Morbi aliquam pulvinar nibh, eget facilisis diam vulputate vitae. Fusce dapibus viverra quam, vel elementum odio facilisis a. Donec et risus elementum mi blandit congue. Sed mattis vitae leo ac pellentesque. Praesent eleifend ligula eu massa scelerisque, a ornare diam pulvinar. Aliquam et sapien eu diam faucibus fringilla. Proin sit amet imperdiet erat, sodales eleifend turpis. In facilisis, leo quis venenatis vehicula, dui ex dignissim turpis, egestas placerat ipsum ante a sapien. Nam non erat nec mi tempus faucibus.

Phasellus at erat vel nulla aliquam pharetra. Integer dui metus, iaculis vel fermentum eget, auctor at turpis. Phasellus ut porta dui. Morbi fermentum massa vitae sapien sagittis faucibus. Nunc sollicitudin cursus ante tristique sagittis. Vivamus vitae lectus mauris. Vestibulum nulla augue, cursus et est nec, vehicula tincidunt felis. Mauris lobortis nulla quis urna sodales pretium. Suspendisse dignissim diam eu luctus consequat. Suspendisse vitae libero rhoncus, commodo sem eget, laoreet justo. Morbi hendrerit, justo sed posuere lacinia, purus urna imperdiet libero, in mollis nulla nulla non libero.

Ut lacinia massa ut purus bibendum, ut vestibulum nulla dapibus. Phasellus tincidunt maximus nibh, non molestie nulla commodo vitae. Nulla sed tellus auctor, interdum urna quis, elementum elit. Aenean malesuada urna dictum ipsum sagittis rutrum. Donec cursus, justo eu interdum auctor, est nibh suscipit purus, cursus interdum enim lectus non ex. Maecenas purus purus, fringilla sit amet tortor ut, ullamcorper ullamcorper nulla. Sed accumsan efficitur quam dignissim facilisis. Etiam eu volutpat leo. Morbi nec varius massa. Sed eu nunc nec risus sagittis lobortis et non felis.`